/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package romanow.abc.desktop.graph;

import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;
import javafx.collections.ObservableList;
import javafx.event.Event;
import javafx.event.EventHandler;
import javafx.scene.Node;
import javafx.scene.chart.ScatterChart;
import javafx.scene.chart.XYChart;
import javafx.scene.control.Tooltip;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.DateAxis;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.xy.XYItemRenderer;
import org.jfree.chart.renderer.xy.XYLineAndShapeRenderer;
import org.jfree.chart.ui.RectangleInsets;
import org.jfree.data.xy.XYDataset;
import romanow.abc.desktop.Client;
import romanow.abc.desktop.I_Success;
import romanow.lep500.I_TrendData;

import javax.swing.*;
import java.awt.*;
import java.text.SimpleDateFormat;
import java.util.ArrayList;

/**
 *
 * @author romanow
 */
public class TrendPanel extends javax.swing.JPanel implements I_Trend{
    private ArrayList<I_TrendData> data = new ArrayList<>();
    private ArrayList<I_TrendData> view = new ArrayList<>();
    private boolean viewReady=true;
    private JPanel chart=null;
    private I_Success back=null;
    XYSeriesCollection dataset = new XYSeriesCollection();
    public void setBack(I_Success bb){
        back = bb;
        Add.setVisible(back!=null);
        }
    ScatterChart<Number, Number> lineChart;
    public TrendPanel(){}
    public void init(Runnable after) {
        initComponents();
        StatList.add("...");
        setVisible(true);
        createJChartPanel();
        revalidate();
        repaint();
        after.run();
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StatList = new java.awt.Choice();
        Remove = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Fore = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        StatListView = new java.awt.Choice();

        setLayout(null);

        StatList.setBackground(new java.awt.Color(204, 204, 204));
        add(StatList);
        StatList.setBounds(80, 5, 300, 30);

        Remove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable/problem.png"))); // NOI18N
        Remove.setBorderPainted(false);
        Remove.setContentAreaFilled(false);
        Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveActionPerformed(evt);
            }
        });
        add(Remove);
        Remove.setBounds(40, 0, 30, 30);

        Clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable/clear.png"))); // NOI18N
        Clear.setBorderPainted(false);
        Clear.setContentAreaFilled(false);
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        add(Clear);
        Clear.setBounds(10, 0, 30, 30);

        Fore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable/right.PNG"))); // NOI18N
        Fore.setBorderPainted(false);
        Fore.setContentAreaFilled(false);
        Fore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForeActionPerformed(evt);
            }
        });
        add(Fore);
        Fore.setBounds(420, 0, 40, 30);

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable/left.png"))); // NOI18N
        Back.setBorderPainted(false);
        Back.setContentAreaFilled(false);
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        add(Back);
        Back.setBounds(380, 0, 40, 30);

        Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable/add.png"))); // NOI18N
        Add.setBorderPainted(false);
        Add.setContentAreaFilled(false);
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        add(Add);
        Add.setBounds(760, 0, 40, 30);

        StatListView.setBackground(new java.awt.Color(204, 204, 204));
        add(StatListView);
        StatListView.setBounds(460, 5, 300, 30);
    }// </editor-fold>//GEN-END:initComponents

    //--------------------------------------------------------------------------
    private String put6(double dd){
        String ss = ""+dd;
        if (ss.length()<4)
            return ss;
        return ss.substring(0,4);
        }
    //==============================================================================
    public void createJChartPanel(){
        JFreeChart chart = createChart(dataset);
        chart.setPadding(new RectangleInsets(2, 2, 2, 2));
        ChartPanel panel = new ChartPanel(chart);
        panel.setFillZoomRectangle(true);
        panel.setMouseWheelEnabled(true);
        panel.setPreferredSize(new Dimension(Client.PanelW - 75, Client.PanelH - 100));
        panel.setBounds(10, 35, Client.PanelW - 75, Client.PanelH - 100);
        add(panel);
        }
    private void refreshJChartPanel() {         // Со всех графиков
        dataset.removeAllSeries();
        for(I_TrendData set : view){
            XYSeries s1 = new XYSeries(set.getTitle());
            double vv[] = set.getY();
            double x0 = set.getX0();
            double dx = set.getDX();
            for(int i=0; i<vv.length;i++,x0+=dx){
                s1.add(x0,vv[i]);
                }
            dataset.addSeries(s1);
            }
        revalidate();
        repaint();
        }

    private JFreeChart createChart(XYDataset dataset){
        JFreeChart chart = ChartFactory.createTimeSeriesChart(
            "",                  // title
            "",           // x-axis label
            "",          // y-axis label
             dataset,                 // data
            true,             // create legend
            true,            // generate tooltips
            false               // generate URLs
            );
        chart.setBackgroundPaint(Color.white);
        XYPlot plot = (XYPlot) chart.getPlot();
        plot.setBackgroundPaint    (Color.lightGray);
        plot.setDomainGridlinePaint(Color.white    );
        plot.setRangeGridlinePaint (Color.white    );
        plot.setAxisOffset(new RectangleInsets(5.0, 5.0, 5.0, 5.0));
        plot.setDomainCrosshairVisible(true);
        plot.setRangeCrosshairVisible(true);
        XYItemRenderer r = plot.getRenderer();
        if (r instanceof XYLineAndShapeRenderer) {
            XYLineAndShapeRenderer renderer = (XYLineAndShapeRenderer) r;
            renderer.setDefaultShapesFilled(true);
            renderer.setDefaultShapesVisible(true);
            //renderer.setBaseShapesVisible   (true);
            //renderer.setBaseShapesFilled    (true);
            renderer.setDrawSeriesLineAsPath(true);
            }
        DateAxis axis = (DateAxis) plot.getDomainAxis();
        axis.setDateFormatOverride(new SimpleDateFormat("dd.MM:k.m.s"));
        return chart;
        }
    //==========================================================================================
    public void paintOne(I_TrendData stat){
        XYChart.Series series = new XYChart.Series();
        final double data[] = stat.getY();
        double x0 = stat.getX0();
        double dx = stat.getDX();
        series.setName(stat.getTitle());
        ObservableList dd = series.getData();
        for(int j=0;j<data.length;j++,x0+=dx){
            XYChart.Data<Double, Double> item = new XYChart.Data<Double, Double>(x0, data[j]);
            dd.add(item);
            }
        lineChart.getData().add(series);
        //----------- Node появляются только после добавления серии !!!!!!!!!!!!
        for(int ii=0;ii<dd.size();ii++){
            XYChart.Data<Double, Double> item = (XYChart.Data<Double, Double>)dd.get(ii);
            final Node node = item.getNode();
            final double yy = data[ii];
            final double xx = stat.getX0()+ii*stat.getDX();
            //------------------ Наведение мыши ----------------------------
            Tooltip.install(node, new Tooltip(String.format("x=%5.2f y=%5.2f",yy,xx)));
            node.setOnMouseEntered(new EventHandler<Event>() {
                @Override
                public void handle(javafx.event.Event event) {
                    node.getStyleClass().add("onHover");
                }
            });
            //Удаление класса после покидание мыши
            node.setOnMouseExited(new EventHandler<javafx.event.Event>() {
                @Override
                public void handle(Event event) {
                    node.getStyleClass().remove("onHover");
                }});
            //--------------------------------------------------------------
            }
        }

    public void addTrend(final I_TrendData histo){
        data.add(histo);
        createStatList();
        refreshJChartPanel();
        }

    public void addTrendView(final I_TrendData histo){
        view.add(histo);
        createStatList();
        refreshJChartPanel();
    }

    @Override
    public void close() {
        removeAll();
        }

    public void createStatList(){
        StatList.removeAll();
        StatList.add("...");
        for(int i=data.size()-1;i>=0;i--)
            StatList.add(data.get(i).getTitle());
        StatListView.removeAll();
        StatListView.add("...");
        for(int i=view.size()-1;i>=0;i--)
            StatListView.add(view.get(i).getTitle());
        }



    private void RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveActionPerformed
        int idx = StatList.getSelectedIndex();
        if (idx==0)
        return;
        final int idx2 = StatList.getItemCount() - idx - 1;
        data.remove(idx2);
        createStatList();
        refreshJChartPanel();
    }//GEN-LAST:event_RemoveActionPerformed

    public void clearAll(){
        StatList.removeAll();
        StatList.add("...");
        final int sz = view.size();
        StatListView.removeAll();
        StatListView.add("...");
        }
    public void repaint(){
        if (!viewReady)
            return;
        clearAll();
        createStatList();
        }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        clearAll();
        data.clear();
        view.clear();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {                                         
        clearAll();
        data.clear();
        view.clear();
        refreshJChartPanel();
    }                                        
    private void AddActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if (back!=null)
            back.onSuccess();
    }

    private void ForeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForeActionPerformed
        final int idx = StatList.getSelectedIndex();
        if (idx==0)
        return;
        final int idx2 = StatList.getItemCount() - idx - 1;
        final I_TrendData zz = data.remove(idx2);
        view.add(zz);
        createStatList();
        refreshJChartPanel();
    }//GEN-LAST:event_ForeActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        final int idx = StatListView.getSelectedIndex();
        if (idx==0)
        return;
        final int idx2 = StatListView.getItemCount() - idx - 1;
        final I_TrendData zz = view.remove(idx2);
        data.add(zz);
        createStatList();
        refreshJChartPanel();
    }//GEN-LAST:event_BackActionPerformed


    @Override
    public void toFront() { }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Back;
    private javax.swing.JButton Clear;
    private javax.swing.JButton Fore;
    private javax.swing.JButton Remove;
    private java.awt.Choice StatList;
    private java.awt.Choice StatListView;
    // End of variables declaration//GEN-END:variables
}
